name: GeminiTranscription
options:
  bundleIdPrefix: com.example.geminitranscription
  deploymentTarget:
    iOS: 18.0
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
targets:
  GeminiTranscription:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.geminitranscription
        INFOPLIST_FILE: Sources/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: GeminiTranscription
        CFBundleDisplayName: GeminiTranscription
        CFBundleIdentifier: com.example.geminitranscription
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSMicrophoneUsageDescription: "We need access to your microphone for audio transcription"
        UIBackgroundModes:
          - audio
